#!/usr/bin/env bash

DOTFILES_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
MODULES_DIR="${DOTFILES_DIR}/modules"

declare -A AVAILABLE_MODULES
AVAILABLE_MODULES=()

declare -a INSTALL_MODULES
INSTALL_MODULES=()

for d in $MODULES_DIR/*/; do
	AVAILABLE_MODULES[$(basename "${d}")]="$d"
done

for a in "$@"; do
	if printf '%s\0' "${!AVAILABLE_MODULES[@]}" | grep -qwz $a; then
		INSTALL_MODULES+=("$a")
	else
		printf "Invalid module: %s\n" "$a" >&2
		exit 1
	fi
done

for module in "${INSTALL_MODULES[@]}"; do
	# Ensure the submodule is initialized
	pushd "$MODULES_DIR"
	git submodule update --init "$module"
	popd

	# Run the modules install script
	${AVAILABLE_MODULES[$module]}/install
done
